kista_rinkeby:
  area_code: "925951"

spanga_tensta:
  area_code: "925952"

hasselby_vallingby:
  area_code: "925953"

bromma:
  area_code: "898740"

kungsholmen_essingeoarna:
  area_code: "898748"

vasastan_norrmalm:
  area_code: "942790"

ostermalm_djurgarden:
  area_code: "925957"

gardet_hjorthagen_norra_djurgarden:
  area_code: "925958"

maria_hogalid_gamla_stan:
  area_code: "925966"

katarina_sofia:
  area_code: "925967"

hammarby_sjostad:
  area_code: "925972"

hagersten_liljeholmen:
  area_code: "925964"

skarholmen_bredang:
  area_code: "925965"

alvsjo:
  area_code: "925971"

gullmarsplan_arsta_ostberga:
  area_code: "925959"

farsta_skondal:
  area_code: "925962"

enskede_skarpnäck:
  area_code: "941046"

stureby_hagsatra_orby:
  area_code: "925960"

botkyrka:
  area_code: "17885"

danderyd:
  area_code: "17892"

ekero:
  area_code: "17896"

haninge:
  area_code: "17928"

huddinge:
  area_code: "17936"

jarfalla:
  area_code: "17951"

lidingo:
  area_code: "17846"

nacka:
  area_code: "17853"

norrtalje:
  area_code: "18003"

nykvarn:
  area_code: "17855"

nynashamn:
  area_code: "18006"

salem:
  area_code: "18019"

sigtuna:
  area_code: "18020"

sollentuna:
  area_code: "18027"

solna:
  area_code: "18028"

sundbyberg:
  area_code: "18042"

sodertalje:
  area_code: "17775"

tyreso:
  area_code: "17792"

taby:
  area_code: "17793"

upplands_vasby:
  area_code: "17798"

upplands_bro:
  area_code: "17799"

vallentuna:
  area_code: "17804"

vaxholm:
  area_code: "17808"

varmdo:
  area_code: "17818"

osteraker:
  area_code: "17769"
