norra_djurgarden:
  area_code: "473397"

gardet:
  area_code: "898475"

kungsholmen:
  area_code: "925968"

ostermalm:
  area_code: "473448"

stora_essingen:
  area_code: "473422"

lilla_essingen:
  area_code: "473386"

hjorthagen:
  area_code: "473369"

vasastan:
  area_code: "925970"

sodermalm:
  area_code: "898472"

norrmalm:
  area_code: "925969"

gamla_stan:
  area_code: "473362"
