kista_rinkeby:
  area_code: "925951"

spanga_tensta:
  area_code: "925952"

hasselby_vallingby:
  area_code: "925953"

bromma:
  area_code: "898740"

kungsholmen_essingeoarna:
  area_code: "898748"

vasastan_norrmalm:
  area_code: "942790"

ostermalm_djurgarden:
  area_code: "925957"

gardet_hjorthagen_norra_djurgarden:
  area_code: "925958"

maria_hogalid_gamla_stan:
  area_code: "925966"

katarina_sofia:
  area_code: "925967"

hammarby_sjostad:
  area_code: "925972"

hagersten_liljeholmen:
  area_code: "925964"

skarholmen_bredang:
  area_code: "925965"

alvsjo:
  area_code: "925971"

gullmarsplan_arsta_ostberga:
  area_code: "925959"

farsta_skondal:
  area_code: "925962"

enskede_skarpnäck:
  area_code: "941046"

stureby_hagsatra_orby:
  area_code: "925960"
